### ISSUE TITLE
能不能有一个一键入SAI目录下所有的vdf的功能？

### ISSUE THREAD

**Issue by ZEERDEER** [pjy612/SteamManifestCache#2]
如题

**Comment by pjy612** [comment]
SAI 支持启动参数的形式 批量添加 app
`SAI.exe app appid1 appid2`
毕竟这玩意 就按需处理 需要的时候 处理一下。
如果要快捷的话 可以自己 根据 要入库的游戏 针对性创建 bat

毕竟 默认 使用不加token的话 没有那么多连接数让下载那么多。
另外 要玩啥就用啥，没啥场景需要一次性 弄好多吧？
贪多嚼不烂的...
